-- Create warehouse, database, and schema
CREATE WAREHOUSE IF NOT EXISTS compute_wh WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS customer_ai_db;
USE DATABASE customer_ai_db;

CREATE SCHEMA IF NOT EXISTS curated;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS ai;
